In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
x=np.array([[20,30],[30,40]])
x

array([[20, 30],
       [30, 40]])

In [4]:
x.ndim

2

In [3]:
P=np.mean(x)
P

30.0

In [ ]:
np.median(x)

In [8]:
np.std(x)

7.0710678118654755

In [9]:
np.cov(x)

array([[50., 50.],
       [50., 50.]])

In [10]:
np.abs(x)

array([[20, 30],
       [30, 40]])

In [11]:
np.any(x)

True

In [12]:
np.all(x)

True

In [4]:
np.min(x)

20

In [5]:
np.max(x)

40

In [6]:
np.argmax(x)

3

In [7]:
np.argmin(x)

0

In [8]:
np.sort(x)

array([[20, 30],
       [30, 40]])

In [9]:
np.argsort(x)

array([[0, 1],
       [0, 1]], dtype=int64)

In [12]:
A=np.arange(12)

In [13]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
A.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
A=A.reshape(6,2)

In [17]:
A

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [18]:
A[0,0]=22

In [19]:
A

array([[22,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [20]:
A[2]

array([4, 5])

In [22]:
ar= np.array([[2,60,40,3],[40,6,50,60],[30,40,7,10]])
ar

array([[ 2, 60, 40,  3],
       [40,  6, 50, 60],
       [30, 40,  7, 10]])

In [23]:
ar.ndim

2

In [24]:
np.sort(ar)

array([[ 2,  3, 40, 60],
       [ 6, 40, 50, 60],
       [ 7, 10, 30, 40]])

In [25]:
ar

array([[ 2, 60, 40,  3],
       [40,  6, 50, 60],
       [30, 40,  7, 10]])

In [26]:
np.min(ar,1)

array([2, 6, 7])

In [27]:
np.max(ar)

60

In [28]:
np.max(ar,0)

array([40, 60, 50, 60])

In [29]:
np.min(ar,axis=1) # row wise

array([2, 6, 7])

In [30]:
np.max(ar,axis=0)

array([40, 60, 50, 60])

In [31]:
a=np.array([20,30,40,50])
a

array([20, 30, 40, 50])

In [32]:
a.sum()

140

In [33]:
b=np.array([[30,50,10],[90,10,60]])
b

array([[30, 50, 10],
       [90, 10, 60]])

In [34]:
np.sum(b,1) #row wise

array([ 90, 160])

In [35]:
np.sum(b,axis=0)

array([120,  60,  70])

In [36]:
np.sum(b,0)

array([120,  60,  70])

In [37]:
np.subtract(b,10)

array([[20, 40,  0],
       [80,  0, 50]])

In [38]:
np.multiply(b,10)

array([[300, 500, 100],
       [900, 100, 600]])