In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pandas_profiling

In [6]:
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [7]:
url='https://raw.githubusercontent.com/reddyprasade/Machine-Learning-Problems-DataSets/master/Regression/QSAR_aquatic_toxicity.csv'

In [8]:
Data=pd.read_csv(url)

In [9]:
Data.head()

Unnamed: 0  TPSA(Tot)  SAacc  H-050  MLOGP  RDCHI  GATS1p  nN  C-040  \
0           0       0.00    0.0      0  2.419  1.225   0.667   0      0   
1           1       0.00    0.0      0  2.638  1.401   0.632   0      0   
2           2       9.23   11.0      0  5.799  2.930   0.486   0      0   
3           3       9.23   11.0      0  5.453  2.887   0.495   0      0   
4           4       9.23   11.0      0  4.068  2.758   0.695   0      0   

   quantitative response  
0                  3.740  
1                  4.330  
2                  7.019  
3                  6.723  
4                  5.979

In [10]:
Data.describe()

Unnamed: 0   TPSA(Tot)       SAacc       H-050       MLOGP       RDCHI  \
count  546.000000  546.000000  546.000000  546.000000  546.000000  546.000000   
mean   272.500000   48.472930   58.869018    0.937729    2.313493    2.492299   
std    157.760895   46.763983   68.166554    1.618632    1.741797    0.811004   
min      0.000000    0.000000    0.000000    0.000000   -6.446000    1.000000   
25%    136.250000   15.790000   11.000000    0.000000    1.232500    1.975000   
50%    272.500000   40.460000   42.683000    0.000000    2.273500    2.344000   
75%    408.750000   70.022500   77.492750    1.000000    3.392750    2.911000   
max    545.000000  347.320000  571.952000   18.000000    9.148000    6.439000   

           GATS1p          nN       C-040  quantitative response  
count  546.000000  546.000000  546.000000             546.000000  
mean     1.046264    1.003663    0.353480               4.658421  
std      0.403677    1.397240    0.806827               1.665215  
min      0.281000    0.000000    0.000000               0.122000  
25%      0.737000    0.000000    0.000000               3.601500  
50%      1.020500    1.000000    0.000000               4.516000  
75%      1.266500    2.000000    0.000000               5.607500  
max      2.500000   11.000000   11.000000              10.047000

In [11]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 546 entries, 0 to 545
Data columns (total 10 columns):
Unnamed: 0               546 non-null int64
TPSA(Tot)                546 non-null float64
SAacc                    546 non-null float64
H-050                    546 non-null int64
MLOGP                    546 non-null float64
RDCHI                    546 non-null float64
GATS1p                   546 non-null float64
nN                       546 non-null int64
C-040                    546 non-null int64
quantitative response    546 non-null float64
dtypes: float64(6), int64(4)
memory usage: 42.7 KB


In [12]:
Data.columns

Index(['Unnamed: 0', 'TPSA(Tot)', 'SAacc', 'H-050', 'MLOGP', 'RDCHI', 'GATS1p',
       'nN', 'C-040', 'quantitative response'],
      dtype='object')

In [13]:
Feature=Data[['TPSA(Tot)', 'SAacc', 'H-050', 'MLOGP', 'RDCHI', 'GATS1p',
       'nN', 'C-040']]

In [14]:
Feature.head()

TPSA(Tot)  SAacc  H-050  MLOGP  RDCHI  GATS1p  nN  C-040
0       0.00    0.0      0  2.419  1.225   0.667   0      0
1       0.00    0.0      0  2.638  1.401   0.632   0      0
2       9.23   11.0      0  5.799  2.930   0.486   0      0
3       9.23   11.0      0  5.453  2.887   0.495   0      0
4       9.23   11.0      0  4.068  2.758   0.695   0      0

In [15]:
Target=Data['quantitative response']

In [16]:
Target.head()

0    3.740
1    4.330
2    7.019
3    6.723
4    5.979
Name: quantitative response, dtype: float64

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test,Y_train,Y_test = train_test_split(Feature,Target)

In [19]:
X_train.shape

(409, 8)

In [20]:
X_test.shape

(137, 8)

In [21]:
Y_train.shape

(409,)

In [22]:
Y_test.shape

(137,)

In [23]:
X_train.head()

TPSA(Tot)   SAacc  H-050  MLOGP  RDCHI  GATS1p  nN  C-040
539      45.82  50.747      0  2.509  2.090   0.617   1      0
193       0.00   0.000      0  2.942  1.924   1.063   0      0
412      45.82  50.747      0  1.887  2.048   0.842   1      0
498      12.53  11.000      0  4.452  2.716   0.490   0      0
274       0.00   0.000      0  3.945  2.344   0.678   0      0

In [24]:
Y_train.head()

539    3.640
193    3.524
412    3.615
498    5.513
274    5.500
Name: quantitative response, dtype: float64

In [25]:
from sklearn.linear_model import LinearRegression

In [26]:
Model = LinearRegression()

In [27]:
Model.fit(X_train, Y_train )

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [28]:
Model.coef_

array([ 0.02724788, -0.01542629,  0.12421074,  0.47720029,  0.43762234,
       -0.60821774, -0.25590323,  0.01622865])

In [29]:
Model.intercept_

2.7832656451987114

In [31]:
Model.normalize

False

## To predict the future

In [33]:
Data.head(1)

Unnamed: 0  TPSA(Tot)  SAacc  H-050  MLOGP  RDCHI  GATS1p  nN  C-040  \
0           0        0.0    0.0      0  2.419  1.225   0.667   0      0   

   quantitative response  
0                   3.74

In [34]:
Model.predict([[9.23,11.0,0,5.799, 2.930, 0.486, 0, 0]])

array([6.61899853])

In [35]:
New_prediction = Model.predict(X_test) 

In [37]:
pd.DataFrame({'Actual Data': Y_test, 'New_Prediction': New_prediction, 'Error': Y_test-New_prediction}).head()

Actual Data  New_Prediction     Error
256        4.830        5.282934 -0.452934
434        2.421        4.436337 -2.015337
206        3.791        4.375637 -0.584637
396        3.850        3.963286 -0.113286
373        3.177        2.690674  0.486326

In [38]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, accuracy_score

In [39]:
mean_squared_error(Y_test, New_prediction)

1.6912571304863024

In [40]:
mean_absolute_error(Y_test, New_prediction)

0.9485479641497955

In [43]:
Model.score(X_train, Y_train)

0.4882244476166429

In [42]:
print("Train Score of a model is : {}".format(Train_Score))

Train Score of a model is : 0.4882244476166429


In [44]:
Test_Score= Model.score(X_test, Y_test )

In [45]:
print("Test Score of a model is : {}".format(Test_Score))

Test Score of a model is : 0.4638691273037071


### Cross Validation

In [48]:
from sklearn.model_selection import cross_val_score


In [50]:
cv=cross_val_score(Model,X_train, Y_train, cv=20)

In [51]:
cv

array([ 0.63761796,  0.00208885,  0.5271297 ,  0.49637784, -0.03922283,
        0.67660959,  0.50362833,  0.36488133,  0.63309124,  0.14887591,
        0.67967335, -1.06163039,  0.05278638,  0.56236988,  0.33799935,
        0.43542049,  0.63098157,  0.48256469,  0.49624572,  0.58004275])

In [52]:
np.mean(cv)

0.3573765857011585

In [53]:
np.median(cv)

0.496311778151671

In [56]:
np.std(cv)

0.39186453343857786

In [57]:
np.max(cv)

0.6796733503949934

In [58]:
np.min(cv)

-1.061630389219126